query FilteredPackagesCounts(
  $search: String
  $matchtags: _text
  $registries: _int8
  $hasfailures: Boolean
  $installed: Boolean
  $notinstalled: Boolean
  $licenses: _text
  $filter: package_rank_vw_bool_exp = {}
) {
  package_search_aggregate(
    args: {
      search: $search
      matchtags: $matchtags
      licenses: $licenses
      isinstalled: $installed
      notinstalled: $notinstalled
      hasfailures: $hasfailures
      registrylist: $registries
    }
    where: { _and: [{ fit: { _gte: 1 } }, $filter] }
  ) {
    aggregate {
      count
    }
  }
}
